// Code generated by VoiceSign Harness (ORCHESTRATE kind=implement). DO NOT EDIT manually.
// 领域层实现（v2 完整实现，2026-10-03）：
//   需求 §4 个性化词典（条目/匹配/纠错安全）+ §5 反馈学习闭环 + 数据五文件（append-only）。
//   验收映射：A4 处理输出 原始/纠错/标点/意图；A8/A9 反馈 ✓/✗ 落盘；A10 黑名单不再改写。
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"
)

// Dictionary 个性化词典（需求 §4.1）：{词条 → 替换目标}，append-only 持久化到 dictionary.jsonl。
// op 语义（契约 v1，与 vhs-asr 一致）：add / update / delete / list。
type Dictionary struct {
	mu      sync.Mutex
	entries map[string]string
	path    string
}

func NewDictionary(dir string) (*Dictionary, error) {
	d := &Dictionary{entries: map[string]string{}, path: filepath.Join(dir, "dictionary.jsonl")}
	_ = os.MkdirAll(dir, 0o755)
	b, err := os.ReadFile(d.path)
	if err == nil {
		for _, ln := range strings.Split(strings.TrimSpace(string(b)), "\n") {
			if ln == "" {
				continue
			}
			var rec struct {
				Op     string `json:"op"`
				Word   string `json:"word"`
				To     string `json:"to,omitempty"`
				UserID string `json:"user_id,omitempty"`
			}
			if json.Unmarshal([]byte(ln), &rec) == nil && rec.Word != "" {
				switch rec.Op {
				case "add", "update":
					if rec.To != "" {
						d.entries[rec.Word] = rec.To
					}
				case "delete":
					delete(d.entries, rec.Word)
				}
			}
		}
	}
	return d, nil
}

// Apply 按 op 执行词典操作并 append-only 留痕（需求 §5.1：改写留痕）。
func (d *Dictionary) Apply(op, word, to string) (map[string]string, error) {
	d.mu.Lock()
	defer d.mu.Unlock()
	rec := map[string]any{"ts": time.Now().UTC().Format(time.RFC3339), "op": op, "word": word}
	switch op {
	case "add", "update":
		if to == "" {
			return nil, fmt.Errorf("op=%s 缺 to", op)
		}
		d.entries[word] = to
		rec["to"] = to
	case "delete":
		delete(d.entries, word)
	case "list":
		return d.snapshotLocked(), nil
	default:
		return nil, fmt.Errorf("未知 op: %s（允许 add/update/delete/list）", op)
	}
	// append-only 留痕
	if op != "list" {
		b, _ := json.Marshal(rec)
		f, err := os.OpenFile(d.path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
		if err != nil {
			return nil, err
		}
		_, _ = f.WriteString(string(b) + "\n")
		_ = f.Close()
	}
	return d.snapshotLocked(), nil
}

func (d *Dictionary) snapshotLocked() map[string]string {
	out := make(map[string]string, len(d.entries))
	for k, v := range d.entries {
		out[k] = v
	}
	return out
}

// Correct 按词典替换（纠错安全：黑名单词条跳过——A10 语义）。
func (d *Dictionary) Correct(text string, bl *Blacklist) (corrected string, hits []string) {
	d.mu.Lock()
	defer d.mu.Unlock()
	corrected = text
	for w, to := range d.entries {
		if bl != nil && bl.Contains(w) {
			continue // 黑名单词条不再改写
		}
		if strings.Contains(corrected, w) {
			corrected = strings.ReplaceAll(corrected, w, to)
			hits = append(hits, w)
		}
	}
	return corrected, hits
}

// Blacklist 改写黑名单（需求 §5.1 第5件：〔这个改错了〕→ 黑名单，再处理不再改写）。
type Blacklist struct {
	mu   sync.Mutex
	set  map[string]bool
	path string
}

func NewBlacklist(dir string) (*Blacklist, error) {
	b := &Blacklist{set: map[string]bool{}, path: filepath.Join(dir, "blacklist.json")}
	if raw, err := os.ReadFile(b.path); err == nil {
		var recs []map[string]any
		if json.Unmarshal(raw, &recs) == nil {
			for _, r := range recs {
				if w, ok := r["word"].(string); ok {
					b.set[w] = true
				}
			}
		}
	}
	return b, nil
}

func (b *Blacklist) Contains(word string) bool {
	b.mu.Lock()
	defer b.mu.Unlock()
	return b.set[word]
}

func (b *Blacklist) Add(word string) error {
	b.mu.Lock()
	defer b.mu.Unlock()
	b.set[word] = true
	recs := make([]map[string]any, 0, len(b.set)+1)
	for w := range b.set {
		recs = append(recs, map[string]any{"word": w})
	}
	recs = append(recs, map[string]any{"ts": time.Now().UTC().Format(time.RFC3339), "action": "add", "word": word})
	b2, _ := json.MarshalIndent(recs, "", "  ")
	return os.WriteFile(b.path, b2, 0o644)
}

// Feedback 反馈学习（需求 §5.1 第4件）：✓/✗ 落 feedback.jsonl（append-only）。
type Feedback struct {
	path string
	mu   sync.Mutex
}

func NewFeedback(dir string) (*Feedback, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	return &Feedback{path: filepath.Join(dir, "feedback.jsonl")}, nil
}

func (f *Feedback) Record(accepted bool, reason, original, corrected string) (map[string]any, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	rec := map[string]any{
		"ts":        time.Now().UTC().Format(time.RFC3339),
		"accepted":  accepted,
		"reason":    reason,
		"original":  original,
		"corrected": corrected,
	}
	b, _ := json.Marshal(rec)
	fh, err := os.OpenFile(f.path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return nil, err
	}
	_, _ = fh.WriteString(string(b) + "\n")
	_ = fh.Close()
	return rec, nil
}

// ClassifyIntent 意图分类（需求 §4.3：8 类 + ORCHESTRATE；触发词驱动的确定性分类）。
func ClassifyIntent(text string) (intent string, params map[string]string) {
	params = map[string]string{}
	switch {
	case strings.Contains(text, "调音") || strings.Contains(text, "音量"):
		intent = "TONE"
	case strings.Contains(text, "写") || strings.Contains(text, "记"):
		intent = "WRITE"
	case strings.Contains(text, "查") || strings.Contains(text, "找"):
		intent = "QUERY"
	case strings.Contains(text, "改") || strings.Contains(text, "换"):
		intent = "EDIT"
	case strings.Contains(text, "删"):
		intent = "DELETE"
	case strings.Contains(text, "读") || strings.Contains(text, "打开"):
		intent = "READ"
	case strings.Contains(text, "提交") || strings.Contains(text, "推"):
		intent = "COMMIT"
	case strings.Contains(text, "实现") || strings.Contains(text, "搭建") || strings.Contains(text, "开发"):
		intent = "ORCHESTRATE"
		params["kind"] = "implement"
	default:
		intent = "UNKNOWN"
	}
	return intent, params
}

// traceStep 性能分步计时（需求 §6 非功能：traces 留痕）。
func traceStep(steps *[]map[string]any, name string, t0 time.Time) time.Duration {
	d := time.Since(t0)
	*steps = append(*steps, map[string]any{"step": name, "ms": d.Milliseconds()})
	return d
}
