// Code generated by VoiceSign Harness (ORCHESTRATE kind=implement). DO NOT EDIT manually.
// 路由实现（v2 完整实现，2026-10-03）：
//   /v1/process（清洗→纠错→意图→响应，含 traces 分步计时）
//   /v1/feedback（✓/✗ → feedback.jsonl；「这个改错了」→ 黑名单）
//   /v1/dictionary（op: add/update/delete/list → dictionary.jsonl）
//   /v1/health
package main

import (
	"encoding/json"
	"net/http"
	"strings"
	"time"
)

// App 是服务装配根对象（领域逻辑在 domain.go）。
type App struct {
	DataDir string
	Dict    *Dictionary
	Black   *Blacklist
	Feedback *Feedback
}

func NewApp(dataDir string) *App {
	a := &App{DataDir: dataDir}
	a.Dict, _ = NewDictionary(dataDir)
	a.Black, _ = NewBlacklist(dataDir)
	a.Feedback, _ = NewFeedback(dataDir)
	return a
}

// RegisterRoutes 注册全部端点。
func (a *App) RegisterRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/v1/health", a.handleHealth)
	mux.HandleFunc("/v1/process", a.handleProcess)
	mux.HandleFunc("/v1/feedback", a.handleFeedback)
	mux.HandleFunc("/v1/dictionary", a.handleDictionary)
}

func (a *App) handleHealth(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "data_dir": a.DataDir})
}

// handleProcess 核心处理：原始 → 纠错（词典+黑名单）→ 意图 → 响应（traces 分步计时）。
func (a *App) handleProcess(w http.ResponseWriter, r *http.Request) {
	var req struct {
		Text     string            `json:"text"`
		UserID   string            `json:"user_id,omitempty"`
		Context  map[string]string `json:"context,omitempty"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "请求体解析失败: " + err.Error()})
		return
	}
	steps := []map[string]any{}
	t0 := time.Now()
	original := strings.TrimSpace(req.Text)
	_ = traceStep(&steps, "clean", t0)

	// 词典纠错（黑名单词条跳过）
	t1 := time.Now()
	corrected, hits := a.Dict.Correct(original, a.Black)
	_ = traceStep(&steps, "dict", t1)

	// 标点断句（punctuated 字段，不动 corrected）
	t2 := time.Now()
	punctuated := punctuate(corrected)
	_ = traceStep(&steps, "punctuate", t2)

	// 意图分类
	t3 := time.Now()
	intent, params := ClassifyIntent(corrected)
	_ = traceStep(&steps, "intent", t3)

	writeJSON(w, http.StatusOK, map[string]any{
		"ok":          true,
		"original":    original,
		"corrected":   corrected,
		"punctuated":  punctuated,
		"intent":      intent,
		"intent_params": params,
		"dictionary_hits": hits,
		"traces":      steps,
		"contract_version": "1",
	})
}

// handleFeedback 反馈学习：✓ accepted=true；✗ accepted=false；「这个改错了」→ 黑名单。
func (a *App) handleFeedback(w http.ResponseWriter, r *http.Request) {
	var req struct {
		Accepted  bool   `json:"accepted"`
		Reason    string `json:"reason,omitempty"`
		Original  string `json:"original,omitempty"`
		Corrected string `json:"corrected,omitempty"`
		Word      string `json:"word,omitempty"` // 「这个改错了」的词典词条
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "请求体解析失败"})
		return
	}
	rec, err := a.Feedback.Record(req.Accepted, req.Reason, req.Original, req.Corrected)
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]any{"ok": false, "error": err.Error()})
		return
	}
	// A10：改错了 → 黑名单（该词条不再改写）
	if !req.Accepted && req.Word != "" {
		if aerr := a.Black.Add(req.Word); aerr == nil {
			rec["blacklisted"] = req.Word
		}
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "feedback": rec})
}

// handleDictionary 词典操作：op add/update/delete/list（契约 v1：op 字段，非 action）。
func (a *App) handleDictionary(w http.ResponseWriter, r *http.Request) {
	var req struct {
		Op   string `json:"op"`
		Word string `json:"word"`
		To   string `json:"to,omitempty"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": "请求体解析失败"})
		return
	}
	entries, err := a.Dict.Apply(req.Op, req.Word, req.To)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"ok": false, "error": err.Error()})
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "entries": entries})
}

// punctuate 标点断句（需求 §4：punctuated 字段内，不动 corrected）。
// 确定性实现：句末标点（。！？）后断行；整体无标点则补句号。RE2 无 lookbehind，用 rune 遍历。
func punctuate(s string) string {
	if s == "" {
		return s
	}
	var b strings.Builder
	runes := []rune(s)
	for i, r := range runes {
		b.WriteRune(r)
		if (r == '。' || r == '！' || r == '？') && i < len(runes)-1 {
			b.WriteRune('\n')
		}
	}
	out := b.String()
	if !strings.ContainsAny(out, "。！？") {
		out = strings.TrimSpace(out) + "。"
	}
	return out
}
