// Code generated by VoiceSign Harness (ORCHESTRATE kind=implement). DO NOT EDIT manually.
// 路由注册：/v1/health 健康检查 + /v1/process 核心处理（契约骨架，TODO 由实现阶段填充）。
package main

import "net/http"

// App 是服务装配根对象（领域逻辑在 domain.go）。
type App struct {
	DataDir string
}

func NewApp(dataDir string) *App { return &App{DataDir: dataDir} }

// RegisterRoutes 注册全部端点（鉴权占位：回环绑定 + 可选 token 头）。
func (a *App) RegisterRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/v1/health", a.handleHealth)
	mux.HandleFunc("/v1/process", a.handleProcess)
}

func (a *App) handleHealth(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "data_dir": a.DataDir})
}

// handleProcess 核心处理端点：TODO 按需求文档实现（意图/词典/反馈/个性化闭环）。
func (a *App) handleProcess(w http.ResponseWriter, r *http.Request) {
	// TODO(实现阶段): 解析请求体 → 领域处理 → 响应（含 traces 留痕）
	writeJSON(w, http.StatusNotImplemented, map[string]any{"ok": false, "error": "骨架未实现"})
}
