// Code generated by VoiceSign Harness (ORCHESTRATE kind=implement). DO NOT EDIT manually.
// 目标产品：个性化后台实现
// 骨架：可编译服务入口（配置/路由/健康检查/鉴权占位）。实现逻辑见 domain.go 与 router.go 的 TODO。
package main

import (
	"encoding/json"
	"flag"
	"log"
	"net/http"
	"os"
)

func envOr(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

func main() {
	addr := flag.String("addr", envOr("VHS_ADDR", "127.0.0.1:8787"), "监听地址（默认回环，非回环拒绝）")
	dataDir := flag.String("data-dir", envOr("VHS_DATA", "./data"), "数据目录")
	flag.Parse()

	if err := os.MkdirAll(*dataDir, 0o755); err != nil {
		log.Fatalf("创建数据目录失败: %v", err)
	}
	app := NewApp(*dataDir)

	mux := http.NewServeMux()
	app.RegisterRoutes(mux) // router.go

	srv := &http.Server{Addr: *addr, Handler: mux}
	log.Printf("服务监听 %s（数据目录 %s）", *addr, *dataDir)
	if err := srv.ListenAndServe(); err != nil {
		log.Fatalf("服务退出: %v", err)
	}
}

// writeJSON 统一 JSON 响应（与 vhs-asr 契约一致）。
func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}
